---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/open-webui
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: openwebui
  values:
    ollama:
      enabled: false
  interval: 10m0s
