---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openwebui
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/open-webui/helm-charts
